### PR TITLE
Allow directory permissions to be a configurable option

### PR DESCRIPTION
**Pull request by madAndroid**
This addresses #3

### CODE REVIEW

**Comment by tagomoris** [comment]
I'm very sorry for late reply.

Diff looks good for me.
Could you squash commits?

**Comment by madAndroid** [comment]
No worries

I'm not sure exactly what happened, but it appears I may have caused the test failures during the rebase - will look into it later this week..

**Comment by madAndroid** [comment]
Going to close and re-open this pull request, had to delete my fork

**Comment by tagomoris** [comment]
I found some problems which exist in original code, and now I'm fixing these.
Please wait a little, and then try to rebase once more?

**Comment by madAndroid** [comment]
Okay great, thanks .. will do :)

On Wed, Jan 14, 2015 at 10:20 AM, TAGOMORI Satoshi <notifications@github.com

**Comment by tagomoris** [comment]
Done.

**Comment by madAndroid** [comment]
Great, thanks .. my fork seems to have gotten into a bad state, my attempts
at rebasing seemed to have caused more issues, so I deleted and reforked
the repo, and have re-submitted the PR as #16.

On Wed, Jan 14, 2015 at 10:34 AM, TAGOMORI Satoshi <notifications@github.com

**Pull request closed without merging**
